### ISSUE TITLE
Support for all management commands

### ISSUE THREAD

**Issue by blueyed** [HassenPy/django-pdb#19]
I would like to use with e.g. `manage.py makemigrations`, too.

**Comment by ryneeverett** [comment]
@tomchristie [From the django-extensions maintainer](https://github.com/django-extensions/django-extensions/issues/483#issuecomment-42824973):

> Happy to consider a Pull Request to merge this functionally into django-extensions if the original author agrees.

**Comment by tomchristie** [comment]
Yup no objection from me on that - probably a good idea! :)
Once it's in raise an issue here for me to tweak the readme directing new users there instead.
