### ISSUE TITLE
Update PYPA package to most/more recent version.

### ISSUE THREAD

**Issue by JohnVonNeumann** [HassenPy/django-pdb#43]
Hey there! Cheers for the package, looking forward to using it, I noticed that #42 was merged in March but the releases on Github list the last official release as happened in July 2017. Can we get a version bump for those of us using pip/pipenv?

Thanks mate.

**Comment by HassenPy** [comment]
done, thanks for the reminder, completely forgot about updating the the pypi, got sucked in by work ...

**Comment by JohnVonNeumann** [comment]
I understand how it is mate! Thanks for the quick reply and thanks for the package!
